// <auto-generated />
using System;
using BinLord.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BinLord.Migrations
{
    [DbContext(typeof(BinLordContext))]
    [Migration("20261001203216_AddCollectionHistory")]
    partial class AddCollectionHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.31");

            modelBuilder.Entity("BinLord.Models.BinCollectionRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BinScheduleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("CollectionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BinScheduleId", "CollectionDate")
                        .IsUnique();

                    b.ToTable("BinCollectionRecords");
                });

            modelBuilder.Entity("BinLord.Models.BinSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("FirstCollectionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("FrequencyWeeks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BinSchedules");
                });

            modelBuilder.Entity("BinLord.Models.BinCollectionRecord", b =>
                {
                    b.HasOne("BinLord.Models.BinSchedule", "BinSchedule")
                        .WithMany()
                        .HasForeignKey("BinScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BinSchedule");
                });
#pragma warning restore 612, 618
        }
    }
}
