// <auto-generated />
using System;
using BinLord.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BinLord.Migrations
{
    [DbContext(typeof(BinLordContext))]
    [Migration("20261001214727_AddNotificationSettings")]
    partial class AddNotificationSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.31");

            modelBuilder.Entity("BinLord.Models.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("BringInAfterHour")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailFrom")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailNotificationsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailTo")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("FeedOccurrencesPerBin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HistoryOccurrencesPerBin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NtfyEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NtfyServerUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NtfyToken")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NtfyTopic")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SmtpHost")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SmtpPassword")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("SmtpPort")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SmtpUseSsl")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SmtpUsername")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("BinLord.Models.BinCollectionRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BinScheduleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BringInReminderSentAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BroughtInAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("CollectionDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PutOutReminderSentAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("TakenOutAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BinScheduleId", "CollectionDate")
                        .IsUnique();

                    b.ToTable("BinCollectionRecords");
                });

            modelBuilder.Entity("BinLord.Models.BinSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("FirstCollectionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("FrequencyWeeks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BinSchedules");
                });

            modelBuilder.Entity("BinLord.Models.BinCollectionRecord", b =>
                {
                    b.HasOne("BinLord.Models.BinSchedule", "BinSchedule")
                        .WithMany()
                        .HasForeignKey("BinScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BinSchedule");
                });
#pragma warning restore 612, 618
        }
    }
}
